spring:
  application:
    name: Redis-Demo
  data:
    redis:
      host: localhost
      port: 10001
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true